# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hrily's Blog
email: hrishihiraskar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I believe in making lives of people easy.  And I do this by programming and designing.  
  I love coding, developing Web and Mobile Apps, contributing to Open Source, and 
  Designing.  I'm currently studying B.Tech. in Computer Engineering at National 
  Institute of Technology, Karnataka.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  hrily
github: https://github.com/Hrily/
facebook: https://facebook.com/hrishi.hiraskar7/
linkedin: https://www.linkedin.com/in/hrishi-hiraskar/
dribbble: https://dribbble.com/hrily/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:year/:month/:day/:title.html

# Old jekyll-paginate pagination logic
paginate: 5
paginate_path: "/page/:num/"